import { CssBaseline, ThemeProvider } from '@material-ui/core'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Background from '../components/Background'
import { Theme } from '../shared/themes'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={Theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Background />
      <Component {...pageProps} />
    </ThemeProvider>
  )
}

export default MyApp
